language: go
go_import_path: github.com/lucab/local_exporter

go:
  - "1.12"

branches:
  only:
    - staging
    - trying
    - master

env:
  global:
    - GO111MODULE="on"
    - GOFLAGS="-mod=vendor"

install:
  - go mod verify

script:
  - go build
  - go test -v ./...
  - docker build --rm -f dist/Dockerfile -t quay.io/lucab/local_exporter:travis .
